import type { FurnitureShape, FurnitureType } from '../types/project'

export type FurniturePreset = {
  id: string
  type: FurnitureType
  name: string
  widthMm: number
  depthMm: number
  heightMm: number
  color: string
  symbol: string
  shape?: FurnitureShape
}

export const furnitureColors = [
  { name: '화이트', value: '#F7F5EF' }, { name: '퓨어 화이트', value: '#FFFFFF' },
  { name: '아이보리', value: '#F2E8D2' }, { name: '크림', value: '#E6D8BE' },
  { name: '베이지', value: '#CDB99B' }, { name: '그레이지', value: '#B7ADA1' },
  { name: '라이트 그레이', value: '#CACCC9' }, { name: '웜 그레이', value: '#9E968C' },
  { name: '차콜', value: '#4B4C49' }, { name: '블랙', value: '#222321' },
  { name: '화이트 오크', value: '#E1C7A0' }, { name: '라이트 오크', value: '#D6B482' },
  { name: '내추럴 오크', value: '#C3955D' }, { name: '애쉬 우드', value: '#B8A486' },
  { name: '내추럴 우드', value: '#B6814F' }, { name: '티크', value: '#98643F' },
  { name: '월넛', value: '#6B432C' }, { name: '다크 월넛', value: '#4B3023' },
  { name: '브라운', value: '#795139' }, { name: '다크 우드', value: '#352820' },
] as const

export const furniturePresets: FurniturePreset[] = [
  { id: 'single-bed', type: 'bed', name: '싱글 침대', widthMm: 1000, depthMm: 2000, heightMm: 450, color: '#d9c8ae', symbol: '🛏' },
  { id: 'super-single-bed', type: 'bed', name: '슈퍼싱글 침대', widthMm: 1100, depthMm: 2000, heightMm: 450, color: '#d5c2a5', symbol: '🛏' },
  { id: 'queen-bed', type: 'bed', name: '퀸 침대', widthMm: 1500, depthMm: 2000, heightMm: 480, color: '#cab99f', symbol: '🛏' },
  { id: 'king-bed', type: 'bed', name: '킹 침대', widthMm: 1650, depthMm: 2100, heightMm: 500, color: '#c4b296', symbol: '🛏' },
  { id: 'sofa-1', type: 'sofa', name: '1인 소파', widthMm: 850, depthMm: 850, heightMm: 800, color: '#8fa99c', symbol: '◫' },
  { id: 'sofa-2', type: 'sofa', name: '2인 소파', widthMm: 1600, depthMm: 850, heightMm: 800, color: '#7d9c8d', symbol: '▰' },
  { id: 'sofa-3', type: 'sofa', name: '3인 소파', widthMm: 2200, depthMm: 900, heightMm: 820, color: '#718f81', symbol: '▰' },
  { id: 'sofa-l', type: 'sofa', name: '카우치 소파', widthMm: 2600, depthMm: 1600, heightMm: 820, color: '#688779', symbol: 'L', shape: 'l-shape' },
  { id: 'dining-2', type: 'table', name: '2인 식탁', widthMm: 800, depthMm: 800, heightMm: 740, color: '#bd8d58', symbol: '▦' },
  { id: 'dining-4', type: 'table', name: '4인 식탁', widthMm: 1200, depthMm: 750, heightMm: 740, color: '#b4814b', symbol: '▦' },
  { id: 'dining-6', type: 'table', name: '6인 식탁', widthMm: 1800, depthMm: 850, heightMm: 740, color: '#a87543', symbol: '▦' },
  { id: 'round-table', type: 'table', name: '원형 테이블', widthMm: 900, depthMm: 900, heightMm: 720, color: '#bd9569', symbol: '●', shape: 'round' },
  { id: 'coffee-table', type: 'table', name: '거실 테이블', widthMm: 1100, depthMm: 550, heightMm: 380, color: '#c09a70', symbol: '▬' },
  { id: 'side-table', type: 'table', name: '사이드 테이블', widthMm: 450, depthMm: 450, heightMm: 520, color: '#c7a47c', symbol: '▪' },
  { id: 'desk-1200', type: 'desk', name: '1200 책상', widthMm: 1200, depthMm: 600, heightMm: 720, color: '#ae8b68', symbol: '▭' },
  { id: 'desk-1600', type: 'desk', name: '1600 책상', widthMm: 1600, depthMm: 700, heightMm: 720, color: '#a27d5a', symbol: '▭' },
  { id: 'desk-l', type: 'desk', name: 'L형 책상', widthMm: 1600, depthMm: 1200, heightMm: 720, color: '#96704e', symbol: 'L', shape: 'l-shape' },
  { id: 'dining-chair', type: 'chair', name: '식탁 의자', widthMm: 450, depthMm: 500, heightMm: 850, color: '#d09b60', symbol: '◩' },
  { id: 'office-chair', type: 'chair', name: '사무용 의자', widthMm: 650, depthMm: 650, heightMm: 1100, color: '#596b66', symbol: '✦' },
  { id: 'stool', type: 'chair', name: '스툴', widthMm: 380, depthMm: 380, heightMm: 450, color: '#bc8c59', symbol: '●' },
  { id: 'wardrobe-1200', type: 'wardrobe', name: '2문 옷장', widthMm: 1200, depthMm: 600, heightMm: 2000, color: '#c9bda9', symbol: '▥' },
  { id: 'wardrobe-1800', type: 'wardrobe', name: '3문 옷장', widthMm: 1800, depthMm: 600, heightMm: 2100, color: '#bfb19b', symbol: '▥' },
  { id: 'dresser', type: 'wardrobe', name: '서랍장', widthMm: 900, depthMm: 450, heightMm: 850, color: '#c5a984', symbol: '▤' },
  { id: 'nightstand', type: 'wardrobe', name: '협탁', widthMm: 450, depthMm: 400, heightMm: 520, color: '#c7aa82', symbol: '▣' },
  { id: 'bookshelf-low', type: 'shelf', name: '낮은 책장', widthMm: 1200, depthMm: 300, heightMm: 800, color: '#a98a67', symbol: '▥' },
  { id: 'bookshelf-tall', type: 'shelf', name: '높은 책장', widthMm: 800, depthMm: 300, heightMm: 1900, color: '#9d7b58', symbol: '▥' },
  { id: 'tv-console', type: 'shelf', name: 'TV 거실장', widthMm: 1800, depthMm: 400, heightMm: 450, color: '#8d745b', symbol: '▰' },
  { id: 'shoe-cabinet', type: 'shelf', name: '신발장', widthMm: 900, depthMm: 350, heightMm: 1100, color: '#a5947f', symbol: '▥' },
  { id: 'low-bed', type: 'bed', name: '저상형 퀸 침대', widthMm: 1600, depthMm: 2100, heightMm: 300, color: '#E6D8BE', symbol: '🛏' },
  { id: 'storage-bed', type: 'bed', name: '수납형 슈퍼싱글 침대', widthMm: 1150, depthMm: 2150, heightMm: 900, color: '#F2E8D2', symbol: '🛏' },
  { id: 'bunk-bed', type: 'bed', name: '이층 침대', widthMm: 1100, depthMm: 2100, heightMm: 1700, color: '#D6B482', symbol: '▤' },
  { id: 'family-bed', type: 'bed', name: '패밀리 침대', widthMm: 2600, depthMm: 2100, heightMm: 850, color: '#E6D8BE', symbol: '🛏' },
  { id: 'single-mattress', type: 'mattress', name: '싱글 매트리스', widthMm: 1000, depthMm: 2000, heightMm: 250, color: '#F7F5EF', symbol: '▱' },
  { id: 'queen-mattress', type: 'mattress', name: '퀸 매트리스', widthMm: 1500, depthMm: 2000, heightMm: 280, color: '#F7F5EF', symbol: '▱' },
  { id: 'topper', type: 'mattress', name: '접이식 토퍼', widthMm: 1100, depthMm: 2000, heightMm: 100, color: '#F2E8D2', symbol: '▱' },
  { id: 'sofa-bed', type: 'sofa', name: '소파베드', widthMm: 1900, depthMm: 950, heightMm: 820, color: '#B7ADA1', symbol: '▰' },
  { id: 'recliner', type: 'sofa', name: '1인 리클라이너', widthMm: 900, depthMm: 1000, heightMm: 1050, color: '#795139', symbol: '◫' },
  { id: 'floor-sofa', type: 'sofa', name: '좌식 소파', widthMm: 1400, depthMm: 800, heightMm: 550, color: '#9E968C', symbol: '▰' },
  { id: 'folding-table', type: 'table', name: '접이식 테이블', widthMm: 1200, depthMm: 600, heightMm: 720, color: '#D6B482', symbol: '▦' },
  { id: 'island-table', type: 'table', name: '아일랜드 식탁', widthMm: 1400, depthMm: 700, heightMm: 900, color: '#E1C7A0', symbol: '▦' },
  { id: 'console-table', type: 'table', name: '콘솔 테이블', widthMm: 1000, depthMm: 350, heightMm: 800, color: '#6B432C', symbol: '▬' },
  { id: 'bench', type: 'chair', name: '2인 벤치', widthMm: 1200, depthMm: 400, heightMm: 450, color: '#C3955D', symbol: '▬' },
  { id: 'armchair', type: 'chair', name: '안락의자', widthMm: 750, depthMm: 800, heightMm: 900, color: '#B7ADA1', symbol: '◫' },
  { id: 'bar-chair', type: 'chair', name: '바체어', widthMm: 450, depthMm: 480, heightMm: 1000, color: '#352820', symbol: '◩' },
  { id: 'folding-chair', type: 'chair', name: '접이식 의자', widthMm: 480, depthMm: 520, heightMm: 820, color: '#CACCC9', symbol: '◩' },
  { id: 'gaming-desk', type: 'desk', name: '게이밍 책상', widthMm: 1400, depthMm: 700, heightMm: 750, color: '#222321', symbol: '▭' },
  { id: 'standing-desk', type: 'desk', name: '모션 데스크', widthMm: 1400, depthMm: 700, heightMm: 1200, color: '#E1C7A0', symbol: '▭' },
  { id: 'study-desk', type: 'desk', name: '학생 책상', widthMm: 1200, depthMm: 650, heightMm: 1200, color: '#F7F5EF', symbol: '▭' },
  { id: 'drawer-5', type: 'wardrobe', name: '5단 서랍장', widthMm: 800, depthMm: 500, heightMm: 1100, color: '#F7F5EF', symbol: '▤' },
  { id: 'kitchen-cabinet', type: 'wardrobe', name: '주방 수납장', widthMm: 1200, depthMm: 500, heightMm: 1800, color: '#F2E8D2', symbol: '▥' },
  { id: 'sliding-wardrobe', type: 'wardrobe', name: '슬라이딩 옷장', widthMm: 2000, depthMm: 650, heightMm: 2200, color: '#B7ADA1', symbol: '▥' },
  { id: 'dress-system', type: 'wardrobe', name: '드레스룸 시스템장', widthMm: 2400, depthMm: 500, heightMm: 2200, color: '#352820', symbol: '▥' },
  { id: 'coat-rack', type: 'wardrobe', name: '스탠드 행거', widthMm: 500, depthMm: 500, heightMm: 1700, color: '#222321', symbol: '⌇' },
  { id: 'wall-shelf', type: 'shelf', name: '벽선반', widthMm: 1000, depthMm: 250, heightMm: 250, color: '#C3955D', symbol: '▬' },
  { id: 'display-cabinet', type: 'shelf', name: '유리 장식장', widthMm: 900, depthMm: 400, heightMm: 1800, color: '#CACCC9', symbol: '▥' },
  { id: 'magazine-rack', type: 'shelf', name: '매거진랙', widthMm: 600, depthMm: 300, heightMm: 900, color: '#B6814F', symbol: '▥' },
  { id: 'full-mirror', type: 'mirror', name: '전신거울', widthMm: 600, depthMm: 80, heightMm: 1800, color: '#222321', symbol: '▯' },
  { id: 'standing-mirror', type: 'mirror', name: '스탠드 거울', widthMm: 500, depthMm: 450, heightMm: 1650, color: '#C3955D', symbol: '◇' },
  { id: 'vanity', type: 'vanity', name: '화장대', widthMm: 1000, depthMm: 450, heightMm: 1350, color: '#F7F5EF', symbol: '▣' },
  { id: 'partition', type: 'partition', name: '공간 파티션', widthMm: 1200, depthMm: 80, heightMm: 1800, color: '#D6B482', symbol: '▥' },
  { id: 'baby-crib', type: 'kids', name: '아기 침대', widthMm: 750, depthMm: 1300, heightMm: 900, color: '#F7F5EF', symbol: '▤' },
  { id: 'kids-desk', type: 'kids', name: '유아 책상세트', widthMm: 800, depthMm: 600, heightMm: 550, color: '#E1C7A0', symbol: '▦' },
  { id: 'toy-storage', type: 'kids', name: '장난감 수납장', widthMm: 900, depthMm: 400, heightMm: 850, color: '#F2E8D2', symbol: '▤' },
  { id: 'refrigerator', type: 'appliance', name: '양문형 냉장고', widthMm: 910, depthMm: 730, heightMm: 1800, color: '#CACCC9', symbol: '▥' },
  { id: 'kimchi-fridge', type: 'appliance', name: '김치냉장고', widthMm: 800, depthMm: 750, heightMm: 1800, color: '#B7ADA1', symbol: '▥' },
  { id: 'washer', type: 'appliance', name: '드럼 세탁기', widthMm: 700, depthMm: 800, heightMm: 1000, color: '#F7F5EF', symbol: '◉' },
  { id: 'washer-dryer', type: 'appliance', name: '워시타워', widthMm: 700, depthMm: 830, heightMm: 1900, color: '#9E968C', symbol: '8' },
  { id: 'tv-65', type: 'appliance', name: '65인치 TV', widthMm: 1450, depthMm: 300, heightMm: 900, color: '#222321', symbol: '▰' },
  { id: 'aircon-stand', type: 'appliance', name: '스탠드 에어컨', widthMm: 380, depthMm: 400, heightMm: 1850, color: '#F7F5EF', symbol: '▯' },
  { id: 'air-purifier', type: 'appliance', name: '공기청정기', widthMm: 400, depthMm: 400, heightMm: 800, color: '#F7F5EF', symbol: '◫' },
  { id: 'robot-vacuum', type: 'appliance', name: '로봇청소기', widthMm: 360, depthMm: 360, heightMm: 100, color: '#222321', symbol: '●' },
  { id: 'dishwasher', type: 'appliance', name: '식기세척기', widthMm: 600, depthMm: 600, heightMm: 820, color: '#CACCC9', symbol: '▥' },
  { id: 'microwave', type: 'appliance', name: '전자레인지', widthMm: 520, depthMm: 420, heightMm: 320, color: '#222321', symbol: '▣' },
  { id: 'water-purifier', type: 'appliance', name: '정수기', widthMm: 260, depthMm: 500, heightMm: 500, color: '#F7F5EF', symbol: '▯' },
  { id: 'projector', type: 'appliance', name: '빔프로젝터', widthMm: 320, depthMm: 240, heightMm: 140, color: '#F7F5EF', symbol: '◉' },
  { id: 'oven', type: 'appliance', name: '빌트인 오븐', widthMm: 600, depthMm: 570, heightMm: 600, color: '#222321', symbol: '▣' },
  { id: 'induction', type: 'appliance', name: '3구 인덕션', widthMm: 600, depthMm: 520, heightMm: 60, color: '#222321', symbol: '●' },
  { id: 'clothing-care', type: 'appliance', name: '의류관리기', widthMm: 600, depthMm: 600, heightMm: 1900, color: '#B7ADA1', symbol: '▥' },
  { id: 'vacuum-dock', type: 'appliance', name: '무선청소기 거치대', widthMm: 300, depthMm: 350, heightMm: 1150, color: '#4B4C49', symbol: '⌇' },
  { id: 'large-plant', type: 'plant', name: '대형 관엽식물', widthMm: 700, depthMm: 700, heightMm: 1800, color: '#52705A', symbol: '♣' },
  { id: 'medium-plant', type: 'plant', name: '중형 화분', widthMm: 450, depthMm: 450, heightMm: 1000, color: '#668061', symbol: '♣' },
  { id: 'small-plant', type: 'plant', name: '테이블 화분', widthMm: 250, depthMm: 250, heightMm: 400, color: '#78936E', symbol: '♣' },
  { id: 'hanging-plant', type: 'plant', name: '행잉 플랜트', widthMm: 400, depthMm: 400, heightMm: 800, color: '#63805D', symbol: '♧' },
  { id: 'monstera', type: 'plant', name: '몬스테라 화분', widthMm: 800, depthMm: 800, heightMm: 1500, color: '#3F654C', symbol: '♣' },
  { id: 'rubber-tree', type: 'plant', name: '고무나무 화분', widthMm: 650, depthMm: 650, heightMm: 1700, color: '#395A45', symbol: '♣' },
  { id: 'olive-tree', type: 'plant', name: '올리브나무 화분', widthMm: 600, depthMm: 600, heightMm: 1600, color: '#6E7B55', symbol: '♣' },
  { id: 'cactus', type: 'plant', name: '대형 선인장', widthMm: 450, depthMm: 450, heightMm: 1300, color: '#65805E', symbol: '♠' },
  { id: 'long-planter', type: 'plant', name: '긴 사각 플랜터', widthMm: 1200, depthMm: 350, heightMm: 900, color: '#55735C', symbol: '♣' },
  { id: 'plant-stand', type: 'plant', name: '화분 스탠드 세트', widthMm: 700, depthMm: 450, heightMm: 900, color: '#78936E', symbol: '♣' },
  { id: 'floor-lamp', type: 'lighting', name: '장스탠드', widthMm: 400, depthMm: 400, heightMm: 1600, color: '#222321', symbol: '◉' },
  { id: 'table-lamp', type: 'lighting', name: '테이블 조명', widthMm: 250, depthMm: 250, heightMm: 450, color: '#E6D8BE', symbol: '◉' },
  { id: 'pendant-light', type: 'lighting', name: '펜던트 조명', widthMm: 500, depthMm: 500, heightMm: 500, color: '#352820', symbol: '◎' },
  { id: 'ceiling-light', type: 'lighting', name: '거실 천장등', widthMm: 900, depthMm: 900, heightMm: 120, color: '#F7F5EF', symbol: '◎' },
  { id: 'track-light', type: 'lighting', name: '레일 조명', widthMm: 1200, depthMm: 100, heightMm: 180, color: '#222321', symbol: '•••' },
  { id: 'wall-light', type: 'lighting', name: '벽 조명', widthMm: 250, depthMm: 180, heightMm: 350, color: '#E6D8BE', symbol: '◐' },
  { id: 'desk-lamp', type: 'lighting', name: '데스크 램프', widthMm: 220, depthMm: 220, heightMm: 500, color: '#4B4C49', symbol: '◉' },
  { id: 'rug', type: 'decor', name: '거실 러그', widthMm: 2000, depthMm: 1500, heightMm: 15, color: '#CDB99B', symbol: '▧' },
  { id: 'round-rug', type: 'decor', name: '원형 러그', widthMm: 1500, depthMm: 1500, heightMm: 15, color: '#B7ADA1', symbol: '●', shape: 'rug-round' },
  { id: 'standing-clock', type: 'decor', name: '스탠딩 시계', widthMm: 450, depthMm: 250, heightMm: 1700, color: '#6B432C', symbol: '◷' },
  { id: 'pet-house', type: 'decor', name: '반려동물 하우스', widthMm: 650, depthMm: 650, heightMm: 700, color: '#E1C7A0', symbol: '⌂' },
  { id: 'cat-tower', type: 'decor', name: '캣타워', widthMm: 700, depthMm: 600, heightMm: 1800, color: '#D6B482', symbol: '♜' },
  { id: 'curtain', type: 'decor', name: '커튼', widthMm: 2000, depthMm: 100, heightMm: 2300, color: '#F2E8D2', symbol: '▥' },
  { id: 'room-divider-curtain', type: 'decor', name: '공간분리 커튼', widthMm: 1500, depthMm: 100, heightMm: 2300, color: '#CDB99B', symbol: '▥' },
  { id: 'laundry-basket', type: 'decor', name: '빨래바구니', widthMm: 450, depthMm: 350, heightMm: 600, color: '#B8A486', symbol: '▧' },
  { id: 'umbrella-stand', type: 'decor', name: '우산꽂이', widthMm: 280, depthMm: 280, heightMm: 600, color: '#4B4C49', symbol: '◌' },
  { id: 'sink-cabinet', type: 'kitchen', name: '싱크대 하부장', widthMm: 900, depthMm: 600, heightMm: 900, color: '#F7F5EF', symbol: '▣', shape: 'sink' },
  { id: 'sink-range-combo', type: 'kitchen', name: '싱크대＋가스레인지', widthMm: 1800, depthMm: 600, heightMm: 900, color: '#F7F5EF', symbol: '▦', shape: 'kitchen-combo' },
  { id: 'kitchen-counter-1200', type: 'kitchen', name: '1200 조리대', widthMm: 1200, depthMm: 600, heightMm: 900, color: '#F2E8D2', symbol: '▤', shape: 'counter' },
  { id: 'kitchen-counter-1800', type: 'kitchen', name: '1800 조리대', widthMm: 1800, depthMm: 600, heightMm: 900, color: '#F2E8D2', symbol: '▤', shape: 'counter' },
  { id: 'gas-range', type: 'kitchen', name: '가스레인지 하부장', widthMm: 600, depthMm: 600, heightMm: 900, color: '#F7F5EF', symbol: '⊙', shape: 'range' },
  { id: 'cooktop', type: 'kitchen', name: '빌트인 쿡탑', widthMm: 600, depthMm: 520, heightMm: 70, color: '#222321', symbol: '⊙', shape: 'cooktop' },
  { id: 'kitchen-island', type: 'kitchen', name: '주방 아일랜드 조리대', widthMm: 1600, depthMm: 800, heightMm: 900, color: '#E1C7A0', symbol: '▦', shape: 'counter' },
  { id: 'kitchen-cart', type: 'kitchen', name: '이동식 주방 카트', widthMm: 700, depthMm: 450, heightMm: 850, color: '#C3955D', symbol: '▤', shape: 'open-shelf' },
  { id: 'desktop-tower', type: 'computer', name: '데스크톱 본체', widthMm: 230, depthMm: 480, heightMm: 470, color: '#222321', symbol: '▯', shape: 'desktop' },
  { id: 'monitor-27', type: 'computer', name: '27인치 모니터', widthMm: 620, depthMm: 220, heightMm: 470, color: '#222321', symbol: '▭', shape: 'monitor' },
  { id: 'monitor-32', type: 'computer', name: '32인치 모니터', widthMm: 720, depthMm: 240, heightMm: 520, color: '#222321', symbol: '▭', shape: 'monitor' },
  { id: 'dual-monitor', type: 'computer', name: '듀얼 모니터', widthMm: 1250, depthMm: 250, heightMm: 500, color: '#222321', symbol: '▭', shape: 'dual-monitor' },
  { id: 'desktop-speakers', type: 'computer', name: '데스크톱 스피커 세트', widthMm: 500, depthMm: 180, heightMm: 260, color: '#4B4C49', symbol: '◉', shape: 'modular' },
  { id: 'printer', type: 'computer', name: '복합기 프린터', widthMm: 480, depthMm: 420, heightMm: 300, color: '#F7F5EF', symbol: '▣' },
  { id: 'oval-table', type: 'table', name: '타원형 식탁', widthMm: 1600, depthMm: 850, heightMm: 740, color: '#D6B482', symbol: '⬭', shape: 'oval' },
  { id: 'modular-sofa', type: 'sofa', name: '모듈형 4인 소파', widthMm: 2800, depthMm: 1000, heightMm: 760, color: '#B7ADA1', symbol: '▰', shape: 'modular' },
  { id: 'corner-sofa', type: 'sofa', name: '코너형 소파', widthMm: 2900, depthMm: 2100, heightMm: 820, color: '#9E968C', symbol: 'L', shape: 'l-shape' },
  { id: 'open-bookshelf-wide', type: 'shelf', name: '와이드 오픈 책장', widthMm: 1600, depthMm: 350, heightMm: 1800, color: '#E1C7A0', symbol: '▥', shape: 'open-shelf' },
  { id: 'modular-drawer', type: 'wardrobe', name: '모듈 서랍 수납장', widthMm: 1200, depthMm: 450, heightMm: 900, color: '#F7F5EF', symbol: '▤', shape: 'drawer' },
]

export const furnitureCategories: { id: 'all' | FurnitureType; label: string }[] = [
  { id: 'all', label: '전체' }, { id: 'bed', label: '침대' }, { id: 'mattress', label: '매트리스' },
  { id: 'sofa', label: '소파' }, { id: 'table', label: '테이블' }, { id: 'desk', label: '책상' },
  { id: 'chair', label: '의자' }, { id: 'wardrobe', label: '수납·옷장' }, { id: 'shelf', label: '선반·책장' },
  { id: 'mirror', label: '거울' }, { id: 'vanity', label: '화장대' }, { id: 'partition', label: '파티션' },
  { id: 'kids', label: '유아동' }, { id: 'kitchen', label: '주방가구' }, { id: 'computer', label: '컴퓨터' }, { id: 'appliance', label: '가전' },
  { id: 'plant', label: '식물' }, { id: 'lighting', label: '조명' }, { id: 'decor', label: '데코' },
]
